Modify signum
openresty/lua-resty-signal pull request #11
Opened 2021-01-03 14:43 UTC by xiaobiaozhao

2021-01-05 03:25 UTC, agentzh requested changes

2021-01-05 03:25 UTC, agentzh commented on resty_signal.c
> +#endif
Needs a blank line here.

2021-01-05 03:25 UTC, agentzh commented on t/signum.t
> +            local macosx_signals = {
Needs a blank line before this line.

2021-01-05 03:25 UTC, agentzh commented on t/signum.t
> +
Should remove this blank line.

2021-01-05 04:37 UTC, xiaobiaozhao commented on resty_signal.c
> +#endif
done

2021-01-05 04:37 UTC, xiaobiaozhao commented on t/signum.t
> +            local macosx_signals = {
done

2021-01-05 04:37 UTC, xiaobiaozhao commented on t/signum.t
> +
done

2021-01-07 13:48 UTC, doujiang24 commented on resty_signal.c
> +    RS_PWR = 30,
need to update the doc for these new signal names.

2021-01-08 03:17 UTC, merged